trigger: none 

pool:
  vmImage: ubuntu-latest
  name: default
  demands:
  - Agent.name -equals L1

stages:
  - stage:
    displayName: "PreBuild"
    jobs:
      - job: BuildAndTestJob
        displayName: 'Build And run associted test'
        steps:
         - task: DotNetCoreCLI@2
           displayName: 'ProjRestore'
           inputs:
             command: 'restore'
             projects: '**/*.csproj'
             feedsToUse: 'select'
           enabled: true
         - task: DotNetCoreCLI@2
           displayName: 'projBuild'
           inputs:
              command: 'build'
              projects: '**/*.csproj'
           enabled: true
         - task: DotNetCoreCLI@2
           displayName: 'Projtest'
           inputs:
             command: 'test'
             projects: '**/*.csproj'
             testRunTitle: '$(build.BuildId)'
           enabled: true
