trigger: none
appendCommitMessageToRunName: false
variables:
   system.debug: true
stages:
- stage: A
  displayName: A
  jobs:
  - job: A1
    displayName: A1
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      name: 'A1PS1'
      inputs:
        targetType: 'inline'
        script: |
          $currentTimeFormatted = Get-Date -Format "yyyy-MM-dd HH:mm:ss"          
          Write-Host "Stage-A_Job-A executed at Current Time: $currentTimeFormatted"         
          Write-Host "##vso[task.setvariable variable=AA1JobVar;isoutput=true] This is Stage A Job A1 variable scoped to Same job"
          Write-Host "##vso[task.setvariable variable=Time_AA1;isOutput=true] Alpha at $currentTimeFormatted"
  - job: A2
    displayName: A2
    dependsOn: A1
    pool:
      vmImage: 'windows-latest'
    variables:
      myVarFromJobA: $[ dependencies.A1.outputs['A1PS1.AA1JobVar'] ] 
    steps:
      - task: PowerShell@2
        name: 'A2PS1'
        inputs:
         targetType: 'inline'
         script: |
          $currentTimeFormatted = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          Write-Host "Current Time: $currentTimeFormatted"          
          Write-Host "##vso[task.setvariable variable=Time_AA2;isOutput=true] Beta at $currentTimeFormatted"    
          Write-Host "Value obtained from Job A1 is $(myVarFromJobA)"
- stage: B
  displayName: B
  dependsOn: A
  jobs:
  - job: 
    displayName: B1
    variables:
      AA1JobAvar: $[stageDependencies.A.A1.outputs['A1PS1.Time_AA1']]
      AA2JobAvar: $[stageDependencies.A.A2.outputs['A2PS1.Time_AA2']]
    steps:
      - task: Bash@3
        displayName: 'Bash task print upstreamm variables'
        inputs:
          targetType: 'inline'
          script: |
            echo $(AA1JobAvar)
            echo $(AA2JobAvar)
