appendCommitMessageToRunName: false
trigger: none

stages:
    - stage: Alpha
      displayName: "Alpha"
      jobs:
          - job: Windows
            pool:
             vmImage: "windows-latest"
            steps:
             - task: PowerShell@2  
               inputs:
                  filePath: '$(System.DefaultWorkingDirectory)\projectid.ps1'
               displayName: "Get Project ID via Powershell script"
               enabled: true
               displayname: "Get Project ID"

