variables:
- name: BuildParameters.searchPatternPack
  value: DotNet6.0.sln
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/6.0
jobs:
- job: Dotnet Version 
  displayName: DoetNet 6.0
  pool:
    vmImage: windows-2019
  steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      searchPatternPack: $(BuildParameters.searchPatternPack)
  - task: DotNetCoreCLI@2
    displayName: dotnet build
...
