appendCommitMessageToRunName: false
trigger: none

stages:
    - stage: first
      displayName: "first"
      jobs:
          - job: Windows
            pool:
             vmImage: "windows-latest"
            steps:
             - task: PowerShell@2  
               inputs:
                  filePath: '<Path to ps script>'
               displayName: "Create Variable Group in given Project"
               enabled: true

